namespace HearthMirror.Enums
{
	public enum GameSaveKeyId
	{
		ADVENTURE_DATA_LOOT = 24,
		ADVENTURE_DATA_GIL = 31,
		ADVENTURE_DATA_TRL = 51,
		ADVENTURE_DATA_DALARAN = 55,
		ADVENTURE_DATA_DALARAN_HEROIC = 344
	}
}